"""Generate WALKTHROUGH.md: the prompt, a baseline run, and real agent runs.

Everything in the output is taken from the code or from a saved run. Nothing is
retyped by hand, so the document cannot drift from what was actually executed.

Episodes are chosen as the one closest to their cell's mean observation count,
not the best or worst, so the examples are representative rather than picked.

Run: python make_walkthrough.py
"""

from __future__ import annotations

import statistics
from pathlib import Path

import agent
from blind_par import FIXED, MOVER, PERIOD, PLACES, ROAMING, STATICS, TARGET, make
from runs_io import pick
from world import World

OUT = Path(__file__).with_name("WALKTHROUGH.md")
L = []          # output lines


def w(s: str = "") -> None:
    L.append(s)


# --------------------------------------------------------------- the prompt

def render_prompt(t_say: int) -> str:
    objects = sorted(list(STATICS) + [MOVER])
    return agent.SYSTEM.format(
        places=", ".join(PLACES), objects=", ".join(objects),
        t_say=t_say, mover=MOVER,
        deadline="unlimited",
        task=f"put {MOVER} on the {TARGET}.")


# ------------------------------------------------------ the baseline, traced

def trace_par(t_do: int, seed: int, order, approach):
    """Same policy as blind_par.play, with every step recorded.

    Kept deliberately parallel to that function. If the two ever disagree the
    numbers in the paper come from blind_par, not from here.
    """
    world = make(t_do, seed)
    steps, n_obs = [], 0
    for place in order:
        if world.finished:
            break
        if approach == "walk-then-look":
            r = world.step(("goto", place))
            steps.append((f"goto({place})", r.render(), world.tick))
            r = world.step(("observe", place)); n_obs += 1
            steps.append((f"observe({place})", r.render(), world.tick))
            if MOVER in getattr(r, "objects", ()):
                r = world.step(("pick", MOVER))
                steps.append((f"pick({MOVER})", r.render(), world.tick))
                if getattr(r, "ok", False):
                    r = world.step(("place", MOVER, TARGET))
                    steps.append((f"place({MOVER},{TARGET})", r.render(), world.tick))
                    break
            continue
        r = world.step(("observe", place)); n_obs += 1
        steps.append((f"observe({place})", r.render(), world.tick))
        if MOVER not in getattr(r, "objects", ()):
            continue
        r = world.step(("goto", place))
        steps.append((f"goto({place})", r.render(), world.tick))
        r = world.step(("pick", MOVER))
        steps.append((f"pick({MOVER})", r.render(), world.tick))
        if getattr(r, "ok", False):
            r = world.step(("place", MOVER, TARGET))
            steps.append((f"place({MOVER},{TARGET})", r.render(), world.tick))
            break
    return steps, n_obs, world.succeeded(MOVER, TARGET)


# ------------------------------------------------------------ real episodes

def representative(records, t_say, t_do, success=None):
    """The episode closest to its cell's mean observation count."""
    eps = [r for r in records if r["t_say"] == t_say and r["t_do"] == t_do
           and (success is None or bool(r["success"]) == success)]
    if not eps:
        return None
    mean = statistics.mean(r["n_obs"] for r in eps)
    return min(eps, key=lambda r: abs(r["n_obs"] - mean)), mean, len(eps)


def dump_episode(rec, cap=None) -> None:
    w("```")
    n = 0
    for t in rec.get("transcript", []):
        p = t.get("parsed")
        act = "(unparseable reply)" if not p else (
            f"{p[0]}({', '.join(p[1:])})" if len(p) > 1 else f"{p[0]}()")
        w(f"  {act:<24} {t.get('env', '')}")
        n += 1
        if cap and n >= cap:
            left = len(rec["transcript"]) - n
            if left > 0:
                w(f"  ... {left} more actions, same pattern ...")
            break
    w("```")


def main() -> None:
    w("# Walkthrough: what the agent sees and what it does")
    w()
    w("Generated by `make_walkthrough.py` from the prompt templates in")
    w("`agent.py`, the baseline policy in `blind_par.py`, and saved episodes in")
    w("`runs/`. Nothing here is retyped, so it cannot drift from what ran.")
    w()
    w("## 1. The world")
    w()
    w(f"Places: {', '.join(PLACES)}. ")
    w(f"The two fixed objects never move ({', '.join(f'{o} on the {p}' for o, p in STATICS.items())}). ")
    w(f"The `{MOVER}` relocates every {PERIOD} ticks among {', '.join(ROAMING)}, ")
    w(f"and the task is to put the `{MOVER}` on the `{TARGET}`.")
    w()
    w("The agent cannot see the room. `observe(place)` is the only action that")
    w("reveals anything, and it costs `L` ticks of world time. During those")
    w(f"ticks the `{MOVER}` keeps moving, so the answer is already out of date")
    w("when it arrives. Every other action costs 1 tick.")
    w()

    # ---- 2. the prompt
    w("## 2. The prompt")
    w()
    w("This is the exact system prompt, at `L = 5`. The only thing that differs")
    w("between conditions is the number on the `observe` line; the stated and")
    w("applied values are set independently, so this number is not always the")
    w("one the world charges.")
    w()
    w("```")
    for line in render_prompt(5).splitlines():
        w(line)
    w("```")
    w()
    w("Each turn the agent replies with one action and receives one line back.")
    w("The reply it sees is a rendered result, for example")
    w("`[tick 5] At sink: cup.` or `[tick 6] Nothing to pick up here.`")
    w()

    # ---- 3. baseline
    w("## 3. The baseline (par)")
    w()
    w("Par is not a solved optimum. It is the mean over all sweep orders of a")
    w("blind policy that knows the rules but not any position, the same")
    w("information the agent has. Two approaches matter:")
    w()
    w("- **commit-on-sight**: look at a place; if the cup is there, walk over")
    w("  and pick. Cheap in observations, but at high `L` the cup has moved by")
    w("  the time you arrive.")
    w("- **walk-then-look**: walk first, then look from where you already are,")
    w("  so the sighting and the pick are adjacent. One extra move per place,")
    w("  and no travel for the cup to escape during.")
    w()
    w("At `L = 0` staleness is impossible and commit-on-sight is best. At")
    w("`L = 5` it stops working and walk-then-look takes over. That switch is")
    w("the mechanism the whole study is about, visible in a policy with no")
    w("learning in it at all.")
    w()
    for t_do, approach in ((0, "commit-on-sight"), (5, "commit-on-sight"),
                           (5, "walk-then-look")):
        order = ROAMING
        steps, n_obs, ok = trace_par(t_do, seed=3, order=order, approach=approach)
        w(f"### L = {t_do}, {approach}, seed 3, sweep order {' -> '.join(order)}")
        w()
        w("```")
        for act, out, tick in steps:
            w(f"  {act:<22} {out}")
        w(f"  -> {n_obs} observations, success = {ok}")
        w("```")
        w()
        if t_do == 5 and approach == "commit-on-sight" and not ok:
            w("The sighting was true when it was made. Five ticks passed while")
            w("the observation resolved and one more during the walk, so the cup")
            w("had already gone. This is the failure mode, in six lines.")
            w()

    # ---- 4. real runs
    w("## 4. Real agent runs")
    w()
    run4 = pick("plain", "random", "dynamic-target", n_cells=4)
    run9 = pick("plain", "random", "dynamic-target", n_cells=9)
    stat = pick("plain", "random", "static-target", n_cells=9)
    w(f"From `{Path(run4['file']).name}` (200 episodes per cell) and")
    w(f"`{Path(stat['file']).name}` for the frozen-world control.")
    w("Each example is the episode closest to its cell's mean observation")
    w("count, so these are typical rather than selected.")
    w()

    cases = [
        ("L = 0, stated 0 -- nothing is stale, nothing is wasted",
         run4, 0, 0, True, None,
         "Three looks, a walk, a pick, a place. This is roughly par (3.00) and "
         "is what competence looks like when information cannot rot."),
        ("L = 5, stated 0 -- the same agent, the same task",
         run4, 0, 5, True, 26,
         "The cup is found and lost repeatedly. Each observation costs five "
         "ticks, and five ticks is most of the cup's eight-tick dwell, so a "
         "sighting is nearly worthless by the time the agent can act. It "
         "succeeds eventually, at roughly seven times the observations."),
        ("L = 5, stated 0 -- a failure",
         run4, 0, 5, False, 22,
         "The same pattern without the lucky ending. 13% of episodes in this "
         "cell end this way."),
        ("L = 5, stated 5 -- one sentence added to the prompt",
         run4, 5, 5, True, 22,
         "The stated figure matches the applied one. Observation falls from "
         "23.01 to 13.79 and success rises from 0.87 to 0.97, so nothing was "
         "traded away. The agent was playing badly and a sentence about time "
         "moved it toward playing better."),
        ("L = 5, frozen world -- the control",
         stat, 0, 5, True, None,
         "Identical latency, identical prompt, but the target is the immobile "
         "bowl. The agent still waits five ticks per look and still watches the "
         "clock advance. It observes about twice and stops. Across all nine "
         "conditions this arm stays between 1.98 and 2.06 observations at "
         "success 1.00, which is the result that rules out a price account."),
    ]
    for title, run, say, do, succ, cap, note in cases:
        got = representative(run["records"], say, do, succ)
        if not got:
            w(f"### {title}"); w(); w("_no episode matched_"); w(); continue
        rec, mean, n = got
        w(f"### {title}")
        w()
        w(f"seed {rec['seed']}, {rec['n_obs']} observations "
          f"(cell mean {mean:.2f} over {n} episodes), "
          f"success {bool(rec['success'])}")
        w()
        dump_episode(rec, cap)
        w()
        w(note)
        w()

    # ---- 5. how to read the numbers
    w("## 5. How to read the numbers")
    w()
    w("| quantity | means |")
    w("|---|---|")
    w("| observations | how many times the agent paid to look |")
    w("| par | what a blind policy averages on the same seeds |")
    w("| success | referee's verdict on true state, never the agent's claim |")
    w("| turns | actions taken, so that looking less by taking longer shows up |")
    w()
    w("The comparison that carries the argument is not any single number. It")
    w("is the same latency applied to a world that moves and a world that does")
    w("not: about 23 observations against about 2.")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(L)} lines)")


if __name__ == "__main__":
    main()
